import Layout from "@components/Layout";
import { useUserQuery } from "@lib/hooks/user";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { user } = useUserQuery();

  return (
    <>
      <Head>
        <title>Book Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>{user && <pre>{JSON.stringify(user, null, 2)}</pre>}</Layout>
    </>
  );
};

export default Home;
