import { Box, Button } from "@chakra-ui/react";
import Layout from "@components/Layout";
import Login from "@components/Login";
import { useLogout, useUserQuery } from "@lib/hooks/user";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: user } = useUserQuery();
  const logout = useLogout();

  return (
    <>
      <Head>
        <title>Book Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {!user ? (
          <Login />
        ) : (
          <>
            <pre>{JSON.stringify(user, null, 2)}</pre>
            <Box textAlign="center">
              <Button onClick={() => logout()}>Sign out</Button>
            </Box>
          </>
        )}
        <p></p>
      </Layout>
    </>
  );
};

export default Home;
